apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "php-k8s-debug.fullname" . }}
data:
  docker-php-ext-xdebug.ini: |-
    zend_extension = xdebug
    xdebug.mode = debug
    xdebug.client_host = host.minikube.internal 
    xdebug.start_with_request = yes
    